name: 'dbt_project'
version: '1.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["models"]
# Define the test paths
test-paths: ["tests"]
# Define the seed paths
seed-paths: ["seeds"]
# Define the macro paths
macro-paths: ["macros"]

models:
  dbt_project:
    materialized: view
    # +schema: TELECOM_SCHEMA  # The schema where DBT will create views/tables

# dbt_project.yml

seeds:
  dbt_project:
    expected_revenue_gender_weekly:
      +column_types:
        WEEK_NUMBER: int
        GENDER: string
        total_revenue_weekly: int

