WITH cleaned_data AS (
    SELECT 
        COALESCE(MSISDN, 'Others') AS MSISDN,
        WEEK_NUMBER,
        COALESCE(REVENUE_USD, 0) AS REVENUE_USD,
        COALESCE(IMEI_TAC, 'Others') AS IMEI_TAC,
        COALESCE(BRAND_NAME, 'Others') AS BRAND_NAME,
        COALESCE(MODEL_NAME, 'Others') AS MODEL_NAME,
        COALESCE(OS_NAME, 'Others') AS OS_NAME,
        COALESCE(OS_VENDOR, 'Others') AS OS_VENDOR,
        COALESCE(GENDER, 'Others') AS GENDER,
        COALESCE(YEAR_OF_BIRTH, 0) AS YEAR_OF_BIRTH,
        COALESCE(SYSTEM_STATUS, 'Others') AS SYSTEM_STATUS,
        COALESCE(MOBILE_TYPE, 'Others') AS MOBILE_TYPE,
        COALESCE(VALUE_SEGMENT, 'Tier 3') AS VALUE_SEGMENT
    FROM combined
)

SELECT * FROM cleaned_data
